os: osx
osx_image: xcode7.2
language: cpp
compiler: clang

before_script:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - gclient
  - fetch v8 $TRAVIS_BUILD_DIR/deps/v8
  - cd $TRAVIS_BUILD_DIR/deps/v8
  - git checkout tags/4.9.385.33
  - gclient sync --with_branch_heads --jobs 16
  - sed -i '' "s/'CLANG_CXX_LANGUAGE_STANDARD': 'gnu++0x'/& ,'CLANG_CXX_LIBRARY': 'libc++'/" $TRAVIS_BUILD_DIR/deps/v8/build/standalone.gypi
  - make native

script:
  - cd $TRAVIS_BUILD_DIR && mkdir b && cd b && cmake .. && make