os: osx
osx_image: xcode7.2
language: cpp
compiler: clang
env: CXX="`which clang++` -std=c++11 -stdlib=libc++" LINK="`which clang++` -std=c++11 -stdlib=libc++" GYP_DEFINES="clang=1 mac_deployment_target=10.7"

before_install:
  - brew update
  - brew install cmake

before_script:
  - bash v8.sh

script:
  - "cd $TRAVIS_BUILD_DIR && mkdir b && cd b && cmake .. && make"